//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMSLotterySystemFront.BLLLottery.NewCcnSendSms {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NewCcnSendSms.CCNSMSServiceSoap")]
    public interface CCNSMSServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 strFactoryID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSmsMTMsg", ReplyAction="*")]
        KMSLotterySystemFront.BLLLottery.NewCcnSendSms.SendSmsMTMsgResponse SendSmsMTMsg(KMSLotterySystemFront.BLLLottery.NewCcnSendSms.SendSmsMTMsgRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 strFactoryID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMTMsgHasProgram", ReplyAction="*")]
        KMSLotterySystemFront.BLLLottery.NewCcnSendSms.SendMTMsgHasProgramResponse SendMTMsgHasProgram(KMSLotterySystemFront.BLLLottery.NewCcnSendSms.SendMTMsgHasProgramRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 UserID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SMS_QueryBalance", ReplyAction="*")]
        KMSLotterySystemFront.BLLLottery.NewCcnSendSms.SMS_QueryBalanceResponse SMS_QueryBalance(KMSLotterySystemFront.BLLLottery.NewCcnSendSms.SMS_QueryBalanceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsMTMsgRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsMTMsg", Namespace="http://tempuri.org/", Order=0)]
        public KMSLotterySystemFront.BLLLottery.NewCcnSendSms.SendSmsMTMsgRequestBody Body;
        
        public SendSmsMTMsgRequest() {
        }
        
        public SendSmsMTMsgRequest(KMSLotterySystemFront.BLLLottery.NewCcnSendSms.SendSmsMTMsgRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsMTMsgRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strFactoryID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strUserID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string strBusinessType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public KMSLotterySystemFront.BLLLottery.NewCcnSendSms.ArrayOfString strMobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string strMTMsg;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string strCC;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string strCodec;
        
        public SendSmsMTMsgRequestBody() {
        }
        
        public SendSmsMTMsgRequestBody(string strFactoryID, string strUserID, string strPassword, string strBusinessType, KMSLotterySystemFront.BLLLottery.NewCcnSendSms.ArrayOfString strMobile, string strMTMsg, string strCC, string strCodec) {
            this.strFactoryID = strFactoryID;
            this.strUserID = strUserID;
            this.strPassword = strPassword;
            this.strBusinessType = strBusinessType;
            this.strMobile = strMobile;
            this.strMTMsg = strMTMsg;
            this.strCC = strCC;
            this.strCodec = strCodec;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsMTMsgResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsMTMsgResponse", Namespace="http://tempuri.org/", Order=0)]
        public KMSLotterySystemFront.BLLLottery.NewCcnSendSms.SendSmsMTMsgResponseBody Body;
        
        public SendSmsMTMsgResponse() {
        }
        
        public SendSmsMTMsgResponse(KMSLotterySystemFront.BLLLottery.NewCcnSendSms.SendSmsMTMsgResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsMTMsgResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SendSmsMTMsgResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strResult;
        
        public SendSmsMTMsgResponseBody() {
        }
        
        public SendSmsMTMsgResponseBody(bool SendSmsMTMsgResult, string strResult) {
            this.SendSmsMTMsgResult = SendSmsMTMsgResult;
            this.strResult = strResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMTMsgHasProgramRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMTMsgHasProgram", Namespace="http://tempuri.org/", Order=0)]
        public KMSLotterySystemFront.BLLLottery.NewCcnSendSms.SendMTMsgHasProgramRequestBody Body;
        
        public SendMTMsgHasProgramRequest() {
        }
        
        public SendMTMsgHasProgramRequest(KMSLotterySystemFront.BLLLottery.NewCcnSendSms.SendMTMsgHasProgramRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMTMsgHasProgramRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strFactoryID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strUserID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string strBusinessType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public KMSLotterySystemFront.BLLLottery.NewCcnSendSms.ArrayOfString strMobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string strMTMsg;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string strCC;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string strCodec;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string strProgramID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string strReserve1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string strReserve2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string strReserve3;
        
        public SendMTMsgHasProgramRequestBody() {
        }
        
        public SendMTMsgHasProgramRequestBody(string strFactoryID, string strUserID, string strPassword, string strBusinessType, KMSLotterySystemFront.BLLLottery.NewCcnSendSms.ArrayOfString strMobile, string strMTMsg, string strCC, string strCodec, string strProgramID, string strReserve1, string strReserve2, string strReserve3) {
            this.strFactoryID = strFactoryID;
            this.strUserID = strUserID;
            this.strPassword = strPassword;
            this.strBusinessType = strBusinessType;
            this.strMobile = strMobile;
            this.strMTMsg = strMTMsg;
            this.strCC = strCC;
            this.strCodec = strCodec;
            this.strProgramID = strProgramID;
            this.strReserve1 = strReserve1;
            this.strReserve2 = strReserve2;
            this.strReserve3 = strReserve3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMTMsgHasProgramResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMTMsgHasProgramResponse", Namespace="http://tempuri.org/", Order=0)]
        public KMSLotterySystemFront.BLLLottery.NewCcnSendSms.SendMTMsgHasProgramResponseBody Body;
        
        public SendMTMsgHasProgramResponse() {
        }
        
        public SendMTMsgHasProgramResponse(KMSLotterySystemFront.BLLLottery.NewCcnSendSms.SendMTMsgHasProgramResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMTMsgHasProgramResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SendMTMsgHasProgramResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strResult;
        
        public SendMTMsgHasProgramResponseBody() {
        }
        
        public SendMTMsgHasProgramResponseBody(bool SendMTMsgHasProgramResult, string strResult) {
            this.SendMTMsgHasProgramResult = SendMTMsgHasProgramResult;
            this.strResult = strResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SMS_QueryBalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SMS_QueryBalance", Namespace="http://tempuri.org/", Order=0)]
        public KMSLotterySystemFront.BLLLottery.NewCcnSendSms.SMS_QueryBalanceRequestBody Body;
        
        public SMS_QueryBalanceRequest() {
        }
        
        public SMS_QueryBalanceRequest(KMSLotterySystemFront.BLLLottery.NewCcnSendSms.SMS_QueryBalanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SMS_QueryBalanceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string PWD;
        
        public SMS_QueryBalanceRequestBody() {
        }
        
        public SMS_QueryBalanceRequestBody(string UserID, string PWD) {
            this.UserID = UserID;
            this.PWD = PWD;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SMS_QueryBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SMS_QueryBalanceResponse", Namespace="http://tempuri.org/", Order=0)]
        public KMSLotterySystemFront.BLLLottery.NewCcnSendSms.SMS_QueryBalanceResponseBody Body;
        
        public SMS_QueryBalanceResponse() {
        }
        
        public SMS_QueryBalanceResponse(KMSLotterySystemFront.BLLLottery.NewCcnSendSms.SMS_QueryBalanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SMS_QueryBalanceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SMS_QueryBalanceResult;
        
        public SMS_QueryBalanceResponseBody() {
        }
        
        public SMS_QueryBalanceResponseBody(int SMS_QueryBalanceResult) {
            this.SMS_QueryBalanceResult = SMS_QueryBalanceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CCNSMSServiceSoapChannel : KMSLotterySystemFront.BLLLottery.NewCcnSendSms.CCNSMSServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CCNSMSServiceSoapClient : System.ServiceModel.ClientBase<KMSLotterySystemFront.BLLLottery.NewCcnSendSms.CCNSMSServiceSoap>, KMSLotterySystemFront.BLLLottery.NewCcnSendSms.CCNSMSServiceSoap {
        
        public CCNSMSServiceSoapClient() {
        }
        
        public CCNSMSServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CCNSMSServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CCNSMSServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CCNSMSServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KMSLotterySystemFront.BLLLottery.NewCcnSendSms.SendSmsMTMsgResponse KMSLotterySystemFront.BLLLottery.NewCcnSendSms.CCNSMSServiceSoap.SendSmsMTMsg(KMSLotterySystemFront.BLLLottery.NewCcnSendSms.SendSmsMTMsgRequest request) {
            return base.Channel.SendSmsMTMsg(request);
        }
        
        public bool SendSmsMTMsg(string strFactoryID, string strUserID, string strPassword, string strBusinessType, KMSLotterySystemFront.BLLLottery.NewCcnSendSms.ArrayOfString strMobile, string strMTMsg, string strCC, string strCodec, out string strResult) {
            KMSLotterySystemFront.BLLLottery.NewCcnSendSms.SendSmsMTMsgRequest inValue = new KMSLotterySystemFront.BLLLottery.NewCcnSendSms.SendSmsMTMsgRequest();
            inValue.Body = new KMSLotterySystemFront.BLLLottery.NewCcnSendSms.SendSmsMTMsgRequestBody();
            inValue.Body.strFactoryID = strFactoryID;
            inValue.Body.strUserID = strUserID;
            inValue.Body.strPassword = strPassword;
            inValue.Body.strBusinessType = strBusinessType;
            inValue.Body.strMobile = strMobile;
            inValue.Body.strMTMsg = strMTMsg;
            inValue.Body.strCC = strCC;
            inValue.Body.strCodec = strCodec;
            KMSLotterySystemFront.BLLLottery.NewCcnSendSms.SendSmsMTMsgResponse retVal = ((KMSLotterySystemFront.BLLLottery.NewCcnSendSms.CCNSMSServiceSoap)(this)).SendSmsMTMsg(inValue);
            strResult = retVal.Body.strResult;
            return retVal.Body.SendSmsMTMsgResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KMSLotterySystemFront.BLLLottery.NewCcnSendSms.SendMTMsgHasProgramResponse KMSLotterySystemFront.BLLLottery.NewCcnSendSms.CCNSMSServiceSoap.SendMTMsgHasProgram(KMSLotterySystemFront.BLLLottery.NewCcnSendSms.SendMTMsgHasProgramRequest request) {
            return base.Channel.SendMTMsgHasProgram(request);
        }
        
        public bool SendMTMsgHasProgram(string strFactoryID, string strUserID, string strPassword, string strBusinessType, KMSLotterySystemFront.BLLLottery.NewCcnSendSms.ArrayOfString strMobile, string strMTMsg, string strCC, string strCodec, string strProgramID, string strReserve1, string strReserve2, string strReserve3, out string strResult) {
            KMSLotterySystemFront.BLLLottery.NewCcnSendSms.SendMTMsgHasProgramRequest inValue = new KMSLotterySystemFront.BLLLottery.NewCcnSendSms.SendMTMsgHasProgramRequest();
            inValue.Body = new KMSLotterySystemFront.BLLLottery.NewCcnSendSms.SendMTMsgHasProgramRequestBody();
            inValue.Body.strFactoryID = strFactoryID;
            inValue.Body.strUserID = strUserID;
            inValue.Body.strPassword = strPassword;
            inValue.Body.strBusinessType = strBusinessType;
            inValue.Body.strMobile = strMobile;
            inValue.Body.strMTMsg = strMTMsg;
            inValue.Body.strCC = strCC;
            inValue.Body.strCodec = strCodec;
            inValue.Body.strProgramID = strProgramID;
            inValue.Body.strReserve1 = strReserve1;
            inValue.Body.strReserve2 = strReserve2;
            inValue.Body.strReserve3 = strReserve3;
            KMSLotterySystemFront.BLLLottery.NewCcnSendSms.SendMTMsgHasProgramResponse retVal = ((KMSLotterySystemFront.BLLLottery.NewCcnSendSms.CCNSMSServiceSoap)(this)).SendMTMsgHasProgram(inValue);
            strResult = retVal.Body.strResult;
            return retVal.Body.SendMTMsgHasProgramResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KMSLotterySystemFront.BLLLottery.NewCcnSendSms.SMS_QueryBalanceResponse KMSLotterySystemFront.BLLLottery.NewCcnSendSms.CCNSMSServiceSoap.SMS_QueryBalance(KMSLotterySystemFront.BLLLottery.NewCcnSendSms.SMS_QueryBalanceRequest request) {
            return base.Channel.SMS_QueryBalance(request);
        }
        
        public int SMS_QueryBalance(string UserID, string PWD) {
            KMSLotterySystemFront.BLLLottery.NewCcnSendSms.SMS_QueryBalanceRequest inValue = new KMSLotterySystemFront.BLLLottery.NewCcnSendSms.SMS_QueryBalanceRequest();
            inValue.Body = new KMSLotterySystemFront.BLLLottery.NewCcnSendSms.SMS_QueryBalanceRequestBody();
            inValue.Body.UserID = UserID;
            inValue.Body.PWD = PWD;
            KMSLotterySystemFront.BLLLottery.NewCcnSendSms.SMS_QueryBalanceResponse retVal = ((KMSLotterySystemFront.BLLLottery.NewCcnSendSms.CCNSMSServiceSoap)(this)).SMS_QueryBalance(inValue);
            return retVal.Body.SMS_QueryBalanceResult;
        }
    }
}
