//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMSLotterySystemFront.SendMessageWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SendMessageWebService.SendMessageWebServiceSoap")]
    public interface SendMessageWebServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 facid 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMessages", ReplyAction="*")]
        KMSLotterySystemFront.SendMessageWebService.SendMessagesResponse SendMessages(KMSLotterySystemFront.SendMessageWebService.SendMessagesRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 facId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerifyMobile", ReplyAction="*")]
        KMSLotterySystemFront.SendMessageWebService.VerifyMobileResponse VerifyMobile(KMSLotterySystemFront.SendMessageWebService.VerifyMobileRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 facId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetVerifyMobile", ReplyAction="*")]
        KMSLotterySystemFront.SendMessageWebService.GetVerifyMobileResponse GetVerifyMobile(KMSLotterySystemFront.SendMessageWebService.GetVerifyMobileRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 userID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NewSendMessages", ReplyAction="*")]
        KMSLotterySystemFront.SendMessageWebService.NewSendMessagesResponse NewSendMessages(KMSLotterySystemFront.SendMessageWebService.NewSendMessagesRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 userID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NewVerifyMobile", ReplyAction="*")]
        KMSLotterySystemFront.SendMessageWebService.NewVerifyMobileResponse NewVerifyMobile(KMSLotterySystemFront.SendMessageWebService.NewVerifyMobileRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 userID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NewGetVerifyMobile", ReplyAction="*")]
        KMSLotterySystemFront.SendMessageWebService.NewGetVerifyMobileResponse NewGetVerifyMobile(KMSLotterySystemFront.SendMessageWebService.NewGetVerifyMobileRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 userID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NewSendMessagesNew", ReplyAction="*")]
        KMSLotterySystemFront.SendMessageWebService.NewSendMessagesNewResponse NewSendMessagesNew(KMSLotterySystemFront.SendMessageWebService.NewSendMessagesNewRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessagesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessages", Namespace="http://tempuri.org/", Order=0)]
        public KMSLotterySystemFront.SendMessageWebService.SendMessagesRequestBody Body;
        
        public SendMessagesRequest() {
        }
        
        public SendMessagesRequest(KMSLotterySystemFront.SendMessageWebService.SendMessagesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMessagesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string facid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sender;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sendto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string message;
        
        public SendMessagesRequestBody() {
        }
        
        public SendMessagesRequestBody(string facid, string sender, string sendto, string message) {
            this.facid = facid;
            this.sender = sender;
            this.sendto = sendto;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessagesResponse", Namespace="http://tempuri.org/", Order=0)]
        public KMSLotterySystemFront.SendMessageWebService.SendMessagesResponseBody Body;
        
        public SendMessagesResponse() {
        }
        
        public SendMessagesResponse(KMSLotterySystemFront.SendMessageWebService.SendMessagesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMessagesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SendMessagesResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string systemstate;
        
        public SendMessagesResponseBody() {
        }
        
        public SendMessagesResponseBody(bool SendMessagesResult, string systemstate) {
            this.SendMessagesResult = SendMessagesResult;
            this.systemstate = systemstate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifyMobileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerifyMobile", Namespace="http://tempuri.org/", Order=0)]
        public KMSLotterySystemFront.SendMessageWebService.VerifyMobileRequestBody Body;
        
        public VerifyMobileRequest() {
        }
        
        public VerifyMobileRequest(KMSLotterySystemFront.SendMessageWebService.VerifyMobileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerifyMobileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string facId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string vifycode;
        
        public VerifyMobileRequestBody() {
        }
        
        public VerifyMobileRequestBody(string facId, string mobile, string vifycode) {
            this.facId = facId;
            this.mobile = mobile;
            this.vifycode = vifycode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifyMobileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerifyMobileResponse", Namespace="http://tempuri.org/", Order=0)]
        public KMSLotterySystemFront.SendMessageWebService.VerifyMobileResponseBody Body;
        
        public VerifyMobileResponse() {
        }
        
        public VerifyMobileResponse(KMSLotterySystemFront.SendMessageWebService.VerifyMobileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerifyMobileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool VerifyMobileResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string systemState;
        
        public VerifyMobileResponseBody() {
        }
        
        public VerifyMobileResponseBody(bool VerifyMobileResult, string systemState) {
            this.VerifyMobileResult = VerifyMobileResult;
            this.systemState = systemState;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVerifyMobileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVerifyMobile", Namespace="http://tempuri.org/", Order=0)]
        public KMSLotterySystemFront.SendMessageWebService.GetVerifyMobileRequestBody Body;
        
        public GetVerifyMobileRequest() {
        }
        
        public GetVerifyMobileRequest(KMSLotterySystemFront.SendMessageWebService.GetVerifyMobileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetVerifyMobileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string facId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string vifycode;
        
        public GetVerifyMobileRequestBody() {
        }
        
        public GetVerifyMobileRequestBody(string facId, string mobile, string vifycode) {
            this.facId = facId;
            this.mobile = mobile;
            this.vifycode = vifycode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVerifyMobileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVerifyMobileResponse", Namespace="http://tempuri.org/", Order=0)]
        public KMSLotterySystemFront.SendMessageWebService.GetVerifyMobileResponseBody Body;
        
        public GetVerifyMobileResponse() {
        }
        
        public GetVerifyMobileResponse(KMSLotterySystemFront.SendMessageWebService.GetVerifyMobileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetVerifyMobileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool GetVerifyMobileResult;
        
        public GetVerifyMobileResponseBody() {
        }
        
        public GetVerifyMobileResponseBody(bool GetVerifyMobileResult) {
            this.GetVerifyMobileResult = GetVerifyMobileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NewSendMessagesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NewSendMessages", Namespace="http://tempuri.org/", Order=0)]
        public KMSLotterySystemFront.SendMessageWebService.NewSendMessagesRequestBody Body;
        
        public NewSendMessagesRequest() {
        }
        
        public NewSendMessagesRequest(KMSLotterySystemFront.SendMessageWebService.NewSendMessagesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NewSendMessagesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userPwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sender;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sendto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string bussinessType;
        
        public NewSendMessagesRequestBody() {
        }
        
        public NewSendMessagesRequestBody(string userID, string userPwd, string sender, string sendto, string message, string bussinessType) {
            this.userID = userID;
            this.userPwd = userPwd;
            this.sender = sender;
            this.sendto = sendto;
            this.message = message;
            this.bussinessType = bussinessType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NewSendMessagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NewSendMessagesResponse", Namespace="http://tempuri.org/", Order=0)]
        public KMSLotterySystemFront.SendMessageWebService.NewSendMessagesResponseBody Body;
        
        public NewSendMessagesResponse() {
        }
        
        public NewSendMessagesResponse(KMSLotterySystemFront.SendMessageWebService.NewSendMessagesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NewSendMessagesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool NewSendMessagesResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string systemState;
        
        public NewSendMessagesResponseBody() {
        }
        
        public NewSendMessagesResponseBody(bool NewSendMessagesResult, string systemState) {
            this.NewSendMessagesResult = NewSendMessagesResult;
            this.systemState = systemState;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NewVerifyMobileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NewVerifyMobile", Namespace="http://tempuri.org/", Order=0)]
        public KMSLotterySystemFront.SendMessageWebService.NewVerifyMobileRequestBody Body;
        
        public NewVerifyMobileRequest() {
        }
        
        public NewVerifyMobileRequest(KMSLotterySystemFront.SendMessageWebService.NewVerifyMobileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NewVerifyMobileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userPwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string vifycode;
        
        public NewVerifyMobileRequestBody() {
        }
        
        public NewVerifyMobileRequestBody(string userID, string userPwd, string mobile, string vifycode) {
            this.userID = userID;
            this.userPwd = userPwd;
            this.mobile = mobile;
            this.vifycode = vifycode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NewVerifyMobileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NewVerifyMobileResponse", Namespace="http://tempuri.org/", Order=0)]
        public KMSLotterySystemFront.SendMessageWebService.NewVerifyMobileResponseBody Body;
        
        public NewVerifyMobileResponse() {
        }
        
        public NewVerifyMobileResponse(KMSLotterySystemFront.SendMessageWebService.NewVerifyMobileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NewVerifyMobileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool NewVerifyMobileResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string systemState;
        
        public NewVerifyMobileResponseBody() {
        }
        
        public NewVerifyMobileResponseBody(bool NewVerifyMobileResult, string systemState) {
            this.NewVerifyMobileResult = NewVerifyMobileResult;
            this.systemState = systemState;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NewGetVerifyMobileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NewGetVerifyMobile", Namespace="http://tempuri.org/", Order=0)]
        public KMSLotterySystemFront.SendMessageWebService.NewGetVerifyMobileRequestBody Body;
        
        public NewGetVerifyMobileRequest() {
        }
        
        public NewGetVerifyMobileRequest(KMSLotterySystemFront.SendMessageWebService.NewGetVerifyMobileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NewGetVerifyMobileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userPwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string vifycode;
        
        public NewGetVerifyMobileRequestBody() {
        }
        
        public NewGetVerifyMobileRequestBody(string userID, string userPwd, string mobile, string vifycode) {
            this.userID = userID;
            this.userPwd = userPwd;
            this.mobile = mobile;
            this.vifycode = vifycode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NewGetVerifyMobileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NewGetVerifyMobileResponse", Namespace="http://tempuri.org/", Order=0)]
        public KMSLotterySystemFront.SendMessageWebService.NewGetVerifyMobileResponseBody Body;
        
        public NewGetVerifyMobileResponse() {
        }
        
        public NewGetVerifyMobileResponse(KMSLotterySystemFront.SendMessageWebService.NewGetVerifyMobileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NewGetVerifyMobileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool NewGetVerifyMobileResult;
        
        public NewGetVerifyMobileResponseBody() {
        }
        
        public NewGetVerifyMobileResponseBody(bool NewGetVerifyMobileResult) {
            this.NewGetVerifyMobileResult = NewGetVerifyMobileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NewSendMessagesNewRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NewSendMessagesNew", Namespace="http://tempuri.org/", Order=0)]
        public KMSLotterySystemFront.SendMessageWebService.NewSendMessagesNewRequestBody Body;
        
        public NewSendMessagesNewRequest() {
        }
        
        public NewSendMessagesNewRequest(KMSLotterySystemFront.SendMessageWebService.NewSendMessagesNewRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NewSendMessagesNewRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userPwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sender;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sendto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string bussinessType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ipServer;
        
        public NewSendMessagesNewRequestBody() {
        }
        
        public NewSendMessagesNewRequestBody(string userID, string userPwd, string sender, string sendto, string message, string bussinessType, string ipServer) {
            this.userID = userID;
            this.userPwd = userPwd;
            this.sender = sender;
            this.sendto = sendto;
            this.message = message;
            this.bussinessType = bussinessType;
            this.ipServer = ipServer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NewSendMessagesNewResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NewSendMessagesNewResponse", Namespace="http://tempuri.org/", Order=0)]
        public KMSLotterySystemFront.SendMessageWebService.NewSendMessagesNewResponseBody Body;
        
        public NewSendMessagesNewResponse() {
        }
        
        public NewSendMessagesNewResponse(KMSLotterySystemFront.SendMessageWebService.NewSendMessagesNewResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NewSendMessagesNewResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool NewSendMessagesNewResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string systemState;
        
        public NewSendMessagesNewResponseBody() {
        }
        
        public NewSendMessagesNewResponseBody(bool NewSendMessagesNewResult, string systemState) {
            this.NewSendMessagesNewResult = NewSendMessagesNewResult;
            this.systemState = systemState;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SendMessageWebServiceSoapChannel : KMSLotterySystemFront.SendMessageWebService.SendMessageWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendMessageWebServiceSoapClient : System.ServiceModel.ClientBase<KMSLotterySystemFront.SendMessageWebService.SendMessageWebServiceSoap>, KMSLotterySystemFront.SendMessageWebService.SendMessageWebServiceSoap {
        
        public SendMessageWebServiceSoapClient() {
        }
        
        public SendMessageWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SendMessageWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendMessageWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendMessageWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KMSLotterySystemFront.SendMessageWebService.SendMessagesResponse KMSLotterySystemFront.SendMessageWebService.SendMessageWebServiceSoap.SendMessages(KMSLotterySystemFront.SendMessageWebService.SendMessagesRequest request) {
            return base.Channel.SendMessages(request);
        }
        
        public bool SendMessages(string facid, string sender, string sendto, string message, out string systemstate) {
            KMSLotterySystemFront.SendMessageWebService.SendMessagesRequest inValue = new KMSLotterySystemFront.SendMessageWebService.SendMessagesRequest();
            inValue.Body = new KMSLotterySystemFront.SendMessageWebService.SendMessagesRequestBody();
            inValue.Body.facid = facid;
            inValue.Body.sender = sender;
            inValue.Body.sendto = sendto;
            inValue.Body.message = message;
            KMSLotterySystemFront.SendMessageWebService.SendMessagesResponse retVal = ((KMSLotterySystemFront.SendMessageWebService.SendMessageWebServiceSoap)(this)).SendMessages(inValue);
            systemstate = retVal.Body.systemstate;
            return retVal.Body.SendMessagesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KMSLotterySystemFront.SendMessageWebService.VerifyMobileResponse KMSLotterySystemFront.SendMessageWebService.SendMessageWebServiceSoap.VerifyMobile(KMSLotterySystemFront.SendMessageWebService.VerifyMobileRequest request) {
            return base.Channel.VerifyMobile(request);
        }
        
        public bool VerifyMobile(string facId, string mobile, string vifycode, out string systemState) {
            KMSLotterySystemFront.SendMessageWebService.VerifyMobileRequest inValue = new KMSLotterySystemFront.SendMessageWebService.VerifyMobileRequest();
            inValue.Body = new KMSLotterySystemFront.SendMessageWebService.VerifyMobileRequestBody();
            inValue.Body.facId = facId;
            inValue.Body.mobile = mobile;
            inValue.Body.vifycode = vifycode;
            KMSLotterySystemFront.SendMessageWebService.VerifyMobileResponse retVal = ((KMSLotterySystemFront.SendMessageWebService.SendMessageWebServiceSoap)(this)).VerifyMobile(inValue);
            systemState = retVal.Body.systemState;
            return retVal.Body.VerifyMobileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KMSLotterySystemFront.SendMessageWebService.GetVerifyMobileResponse KMSLotterySystemFront.SendMessageWebService.SendMessageWebServiceSoap.GetVerifyMobile(KMSLotterySystemFront.SendMessageWebService.GetVerifyMobileRequest request) {
            return base.Channel.GetVerifyMobile(request);
        }
        
        public bool GetVerifyMobile(string facId, string mobile, string vifycode) {
            KMSLotterySystemFront.SendMessageWebService.GetVerifyMobileRequest inValue = new KMSLotterySystemFront.SendMessageWebService.GetVerifyMobileRequest();
            inValue.Body = new KMSLotterySystemFront.SendMessageWebService.GetVerifyMobileRequestBody();
            inValue.Body.facId = facId;
            inValue.Body.mobile = mobile;
            inValue.Body.vifycode = vifycode;
            KMSLotterySystemFront.SendMessageWebService.GetVerifyMobileResponse retVal = ((KMSLotterySystemFront.SendMessageWebService.SendMessageWebServiceSoap)(this)).GetVerifyMobile(inValue);
            return retVal.Body.GetVerifyMobileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KMSLotterySystemFront.SendMessageWebService.NewSendMessagesResponse KMSLotterySystemFront.SendMessageWebService.SendMessageWebServiceSoap.NewSendMessages(KMSLotterySystemFront.SendMessageWebService.NewSendMessagesRequest request) {
            return base.Channel.NewSendMessages(request);
        }
        
        public bool NewSendMessages(string userID, string userPwd, string sender, string sendto, string message, string bussinessType, out string systemState) {
            KMSLotterySystemFront.SendMessageWebService.NewSendMessagesRequest inValue = new KMSLotterySystemFront.SendMessageWebService.NewSendMessagesRequest();
            inValue.Body = new KMSLotterySystemFront.SendMessageWebService.NewSendMessagesRequestBody();
            inValue.Body.userID = userID;
            inValue.Body.userPwd = userPwd;
            inValue.Body.sender = sender;
            inValue.Body.sendto = sendto;
            inValue.Body.message = message;
            inValue.Body.bussinessType = bussinessType;
            KMSLotterySystemFront.SendMessageWebService.NewSendMessagesResponse retVal = ((KMSLotterySystemFront.SendMessageWebService.SendMessageWebServiceSoap)(this)).NewSendMessages(inValue);
            systemState = retVal.Body.systemState;
            return retVal.Body.NewSendMessagesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KMSLotterySystemFront.SendMessageWebService.NewVerifyMobileResponse KMSLotterySystemFront.SendMessageWebService.SendMessageWebServiceSoap.NewVerifyMobile(KMSLotterySystemFront.SendMessageWebService.NewVerifyMobileRequest request) {
            return base.Channel.NewVerifyMobile(request);
        }
        
        public bool NewVerifyMobile(string userID, string userPwd, string mobile, string vifycode, out string systemState) {
            KMSLotterySystemFront.SendMessageWebService.NewVerifyMobileRequest inValue = new KMSLotterySystemFront.SendMessageWebService.NewVerifyMobileRequest();
            inValue.Body = new KMSLotterySystemFront.SendMessageWebService.NewVerifyMobileRequestBody();
            inValue.Body.userID = userID;
            inValue.Body.userPwd = userPwd;
            inValue.Body.mobile = mobile;
            inValue.Body.vifycode = vifycode;
            KMSLotterySystemFront.SendMessageWebService.NewVerifyMobileResponse retVal = ((KMSLotterySystemFront.SendMessageWebService.SendMessageWebServiceSoap)(this)).NewVerifyMobile(inValue);
            systemState = retVal.Body.systemState;
            return retVal.Body.NewVerifyMobileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KMSLotterySystemFront.SendMessageWebService.NewGetVerifyMobileResponse KMSLotterySystemFront.SendMessageWebService.SendMessageWebServiceSoap.NewGetVerifyMobile(KMSLotterySystemFront.SendMessageWebService.NewGetVerifyMobileRequest request) {
            return base.Channel.NewGetVerifyMobile(request);
        }
        
        public bool NewGetVerifyMobile(string userID, string userPwd, string mobile, string vifycode) {
            KMSLotterySystemFront.SendMessageWebService.NewGetVerifyMobileRequest inValue = new KMSLotterySystemFront.SendMessageWebService.NewGetVerifyMobileRequest();
            inValue.Body = new KMSLotterySystemFront.SendMessageWebService.NewGetVerifyMobileRequestBody();
            inValue.Body.userID = userID;
            inValue.Body.userPwd = userPwd;
            inValue.Body.mobile = mobile;
            inValue.Body.vifycode = vifycode;
            KMSLotterySystemFront.SendMessageWebService.NewGetVerifyMobileResponse retVal = ((KMSLotterySystemFront.SendMessageWebService.SendMessageWebServiceSoap)(this)).NewGetVerifyMobile(inValue);
            return retVal.Body.NewGetVerifyMobileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KMSLotterySystemFront.SendMessageWebService.NewSendMessagesNewResponse KMSLotterySystemFront.SendMessageWebService.SendMessageWebServiceSoap.NewSendMessagesNew(KMSLotterySystemFront.SendMessageWebService.NewSendMessagesNewRequest request) {
            return base.Channel.NewSendMessagesNew(request);
        }
        
        public bool NewSendMessagesNew(string userID, string userPwd, string sender, string sendto, string message, string bussinessType, string ipServer, out string systemState) {
            KMSLotterySystemFront.SendMessageWebService.NewSendMessagesNewRequest inValue = new KMSLotterySystemFront.SendMessageWebService.NewSendMessagesNewRequest();
            inValue.Body = new KMSLotterySystemFront.SendMessageWebService.NewSendMessagesNewRequestBody();
            inValue.Body.userID = userID;
            inValue.Body.userPwd = userPwd;
            inValue.Body.sender = sender;
            inValue.Body.sendto = sendto;
            inValue.Body.message = message;
            inValue.Body.bussinessType = bussinessType;
            inValue.Body.ipServer = ipServer;
            KMSLotterySystemFront.SendMessageWebService.NewSendMessagesNewResponse retVal = ((KMSLotterySystemFront.SendMessageWebService.SendMessageWebServiceSoap)(this)).NewSendMessagesNew(inValue);
            systemState = retVal.Body.systemState;
            return retVal.Body.NewSendMessagesNewResult;
        }
    }
}
